#!/usr/local/bin/python

from munin.tomcat import MuninTomcatPlugin

class MuninJBossMemoryPlugin(MuninTomcatPlugin):
    
    title = 'JVM Memory'
    vlabel = 'RAM Memory in MB'
    args = '--base 1000'

    fields = (
        ('max', dict(
            label = 'Max memory',
            type = 'GAUGE',
            draw = 'LINE2',
            min = '0',
        )),
        ('total', dict(
            label = 'Total memory',
            type = 'GAUGE',
            draw = 'LINE2',
            min = '0',
        )),
        ('free', dict(
            label = 'Free memory',
            type = 'GAUGE',
            draw = 'LINE2',
            min = '0',
        ))
    )
    
    def execute(self):
        stats = self.get_memory_stats()
        
        return dict(
            max = stats['max'],
            total = stats['total'],
            free = stats['free'],
        )
        
if __name__ == '__main__':
    MuninJBossMemoryPlugin().run()